---
# Répertoire source tools/vault/ et destination sur le remote
vault_install_src: "{{ playbook_dir }}/../tools/vault/"
vault_install_dest: /tmp/vault-install
vault_namespace: vault
vault_helm_repo_name: hashicorp
vault_helm_repo_url: https://helm.releases.hashicorp.com
vault_helm_release_name: vault
vault_helm_chart: hashicorp/vault
vault_helm_timeout: 5m
vault_node_port: 30200
