apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: mongodb
type: Opaque
stringData:
  # Modifier ces valeurs avant installation.
  MONGO_INITDB_ROOT_USERNAME: admin
  MONGO_INITDB_ROOT_PASSWORD: "mongopAss123!"
  MONGO_APP_USERNAME: iyadris
  MONGO_APP_PASSWORD: "myappPass123!"
  MONGO_APP_DATABASE:
